package ch.deeppay.spring.openapi;

import java.net.URI;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "DeepPayProblem1", description = "Uniform formatting of the error of a response according to https://datatracker.ietf.org/doc/html/rfc7807 be implemented.")
public interface OpenApiDeepPayProblem {

  @Schema(description = "Uri reference that identifies the problem type", example = "https://docs.api.deeppay.swiss/ebanking/interfaces/some_error")
  URI getType();

  @Schema(description = "A short summary of the problem", example = "Validation error")
  String getTitle();

  @Schema(description = "An detailed explanation to this occurrence of the problem", example = "Entered value on field 'xyz' was invalid")
  String getDetail();

  @Schema(description = "The HTTP status code generated by the origin server for this occurrence of the problem", example = "[Http status code]")
  int getStatus();

  @Schema(description = "A relative uri path that identifies the specific occurrence of the problem ",  example = "/SubPath")
  String getInstance();

  @Schema(description = "Trace id of a the request where the problem occurred", example = "112233445566")
  String getTraceId();

  @Schema(description = "Session trace id where the problem occurred", example = "665544332211")
  String getSessionId();

}
